"""empty message

Revision ID: 51fc46267312
Revises: ab098f77a1b9
Create Date: 2025-04-26 19:46:06.622039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fc46267312'
down_revision = 'ab098f77a1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_id', sa.String(length=50), nullable=False))
        batch_op.drop_column('celery_task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_task_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('celery_id')

    # ### end Alembic commands ###
