"""empty message

Revision ID: ab098f77a1b9
Revises: 3855ccc4c52b
Create Date: 2025-04-06 19:50:48.518533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab098f77a1b9'
down_revision = '3855ccc4c52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_task_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('celery_task_id')

    # ### end Alembic commands ###
